export const books = [
  {
    id: 1,
    title: "Milk and Honey",
    author: "Rupi Kaur",
    category: "Best Seller",
    categoryColor: "bg-gray-800",
    price: 125000,
    rating: 4.8,
    sold: 1200,
    pages: 208,
    language: "Inggris",
    publishDate: "2015",
    desc: "Koleksi puisi dan prosa tentang cara bertahan hidup. Tentang pengalaman kekerasan, pelecehan, cinta, kehilangan, dan feminitas.",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 2,
    title: "How Innovation Works",
    author: "Matt Ridley",
    category: "Trending",
    categoryColor: "bg-yellow-500",
    price: 185000,
    rating: 4.5,
    sold: 850,
    pages: 416,
    language: "Indonesia",
    publishDate: "2020",
    desc: "Matt Ridley membahas bagaimana inovasi mengubah dunia dan mengapa kebebasan adalah kunci bagi kemajuan teknologi manusia.",
    image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 3,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Finance",
    categoryColor: "bg-green-600",
    price: 99000,
    rating: 4.9,
    sold: 5000,
    pages: 256,
    language: "Indonesia",
    publishDate: "2021",
    desc: "Pelajaran abadi mengenai kekayaan, ketamakan, dan kebahagiaan. Mengatur uang bukan hanya soal angka, tapi soal perilaku.",
    image: "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 4,
    title: "Zero to One",
    author: "Peter Thiel",
    category: "Novel",
    categoryColor: "bg-orange-600",
    price: 145000,
    rating: 4.7,
    sold: 2100,
    pages: 224,
    language: "Inggris",
    publishDate: "2014",
    desc: "Buku legendaris tentang cara membangun startup dan masa depan. Peter Thiel mengajarkan cara berpikir kontrarian.",
    image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=800",
  },
];
